"""empty message

Revision ID: d91550d42a11
Revises: a6ac961f29f5
Create Date: 2023-03-29 21:34:39.275187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91550d42a11'
down_revision = 'a6ac961f29f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matches_won_frozen', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('matches_won_frozen')

    # ### end Alembic commands ###
